# Generated by Django 3.1.6 on 2023-02-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20230202_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='maintenanceStatus',
            field=models.BooleanField(default=1),
        ),
    ]
