# Generated by Django 3.1.6 on 2023-02-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20230206_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='maintenanceEnd',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='maintenanceStart',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
