# Generated by Django 3.1.6 on 2023-02-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20230206_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='maintenanceStatus',
            field=models.IntegerField(default=1),
        ),
    ]
