# Generated by Django 3.1.6 on 2023-02-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20230206_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='lastmaintenancestaff',
            new_name='maintenancestaffemail',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='nextmaintenance',
            new_name='maintenancestaffname',
        ),
    ]
