# Generated by Django 3.1.6 on 2023-01-30 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('rack_monitor', '0001_initial'),
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/cam/')),
                ('timeStamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AssetLocationChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('removedFrom', models.IntegerField(default=0)),
                ('placedIN', models.IntegerField(default=0)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.floormap')),
                ('macid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rack_monitor.rack')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('lastseen', models.DateTimeField()),
                ('temperature', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('energy', models.FloatField(default=0)),
                ('endTime', models.DateTimeField(auto_now_add=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.floormap')),
                ('macid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
                ('rack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rack_monitor.rack')),
            ],
        ),
    ]
