# Generated by Django 3.1.6 on 2023-01-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloorMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('image', models.ImageField(upload_to='static/tracking/')),
            ],
        ),
    ]
