# Generated by Django 3.1.6 on 2023-01-30 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterGateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatewayid', models.CharField(max_length=20, unique=True)),
                ('lastseen', models.DateTimeField(auto_now=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.floormap')),
            ],
        ),
        migrations.CreateModel(
            name='SlaveGateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatewayid', models.CharField(max_length=20, unique=True)),
                ('lastseen', models.DateTimeField(auto_now=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.mastergateway')),
            ],
        ),
    ]
