# Generated by Django 3.1.6 on 2023-01-30 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macid', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(default=None, max_length=200, unique=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('tempLow', models.FloatField()),
                ('tempHigh', models.FloatField()),
                ('humiLow', models.FloatField(default=0.0)),
                ('humiHigh', models.FloatField(default=0.0)),
                ('capacity', models.FloatField()),
                ('energy', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.floormap')),
            ],
        ),
        migrations.CreateModel(
            name='RackWiseAvgTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempFAvg', models.FloatField(default=0.0)),
                ('tempBAvg', models.FloatField(default=0.0)),
                ('humiFAvg', models.FloatField(default=0.0)),
                ('humiBAvg', models.FloatField(default=0.0)),
                ('energy', models.FloatField(default=0.0)),
                ('maxTemp', models.FloatField(default=0.0)),
                ('minTemp', models.FloatField(default=0.0)),
                ('maxHumi', models.FloatField(default=0.0)),
                ('minHumi', models.FloatField(default=0.0)),
                ('count', models.IntegerField()),
                ('lastseen', models.DateTimeField()),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rack_monitor.rack')),
            ],
        ),
        migrations.CreateModel(
            name='RackWiseAssetCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=0.0)),
                ('time', models.DateTimeField(auto_now=True, null=True)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rack_monitor.rack')),
            ],
        ),
    ]
